// Images
import ProdOne from '../src/assets/product1.png'
import ProdTwo from '../src/assets/product2.png'
import ProdThree from '../src/assets/product3.png'
import ProdFour from '../src/assets/product4.png'
import ProdFive from '../src/assets/product5.png'
import ProdSix from '../src/assets/product6.png'
import ProdSeven from '../src/assets/product7.png'
import ProdEight from '../src/assets/product8.png'
import ProdNine from '../src/assets/product9.png'
import ProdTen from '../src/assets/product10.png'
import ProdEleven from '../src/assets/product11.png'
import ProdTwelve from '../src/assets/product12.png'

let data = [
    {
        id: 1,
        title: "Product One",
        description: "Black",
        price: "$44.00",
        image: ProdOne,
    },
    {
        id: 2,
        title: "Product Two",
        description: "Black",
        price: "$44.00",
        image: ProdTwo,
    },
    {
        id: 3,
        title: "Product Three",
        description: "Black",
        price: "$44.00",
        image: ProdThree,
    },
    {
        id: 4,
        title: "Product Four",
        description: "Black",
        price: "$44.00",
        image: ProdFour,
    },
    {
        id: 5,
        title: "Product Five",
        description: "Black",
        price: "$44.00",
        image: ProdFive,
    },
    {
        id: 3,
        title: "Product Three",
        description: "Black",
        price: "$44.00",
        image: ProdThree,
    },
    {
        id: 4,
        title: "Product Four",
        description: "Black",
        price: "$44.00",
        image: ProdFour,
    },
    {
        id: 5,
        title: "Product Five",
        description: "Black",
        price: "$44.00",
        image: ProdFive,
    },
    {
        id: 3,
        title: "Product Three",
        description: "Black",
        price: "$44.00",
        image: ProdThree,
    },
    {
        id: 4,
        title: "Product Four",
        description: "Black",
        price: "$44.00",
        image: ProdFour,
    },
    {
        id: 5,
        title: "Product Five",
        description: "Black",
        price: "$44.00",
        image: ProdFive,
    },
    {
        id: 3,
        title: "Product Three",
        description: "Black",
        price: "$44.00",
        image: ProdThree,
    },
    {
        id: 4,
        title: "Product Four",
        description: "Black",
        price: "$44.00",
        image: ProdFour,
    },
    {
        id: 5,
        title: "Product Five",
        description: "Black",
        price: "$44.00",
        image: ProdFive,
    },
    {
        id: 3,
        title: "Product Three",
        description: "Black",
        price: "$44.00",
        image: ProdThree,
    },
    {
        id: 4,
        title: "Product Four",
        description: "Black",
        price: "$44.00",
        image: ProdFour,
    },
    {
        id: 5,
        title: "Product Five",
        description: "Black",
        price: "$44.00",
        image: ProdFive,
    },
    {
        id: 3,
        title: "Product Three",
        description: "Black",
        price: "$44.00",
        image: ProdThree,
    },
    {
        id: 4,
        title: "Product Four",
        description: "Black",
        price: "$44.00",
        image: ProdFour,
    },
    {
        id: 5,
        title: "Product Five",
        description: "Black",
        price: "$44.00",
        image: ProdFive,
    },
    {
        id: 6,
        title: "Product Six",
        description: "Black",
        price: "$44.00",
        image: ProdSix,
    },
    {
        id: 7,
        title: "Product Seven",
        description: "Black",
        price: "$44.00",
        image: ProdSeven,
    },
    {
        id: 8,
        title: "Product Eight",
        description: "Black",
        price: "$44.00",
        image: ProdEight,
    },
    {
        id: 6,
        title: "Product Six",
        description: "Black",
        price: "$44.00",
        image: ProdSix,
    },
    {
        id: 7,
        title: "Product Seven",
        description: "Black",
        price: "$44.00",
        image: ProdSeven,
    },
    {
        id: 8,
        title: "Product Eight",
        description: "Black",
        price: "$44.00",
        image: ProdEight,
    },
    {
        id: 6,
        title: "Product Six",
        description: "Black",
        price: "$44.00",
        image: ProdSix,
    },
    {
        id: 7,
        title: "Product Seven",
        description: "Black",
        price: "$44.00",
        image: ProdSeven,
    },
    {
        id: 8,
        title: "Product Eight",
        description: "Black",
        price: "$44.00",
        image: ProdEight,
    },
    {
        id: 6,
        title: "Product Six",
        description: "Black",
        price: "$44.00",
        image: ProdSix,
    },
    {
        id: 7,
        title: "Product Seven",
        description: "Black",
        price: "$44.00",
        image: ProdSeven,
    },
    {
        id: 8,
        title: "Product Eight",
        description: "Black",
        price: "$44.00",
        image: ProdEight,
    },
    {
        id: 6,
        title: "Product Six",
        description: "Black",
        price: "$44.00",
        image: ProdSix,
    },
    {
        id: 7,
        title: "Product Seven",
        description: "Black",
        price: "$44.00",
        image: ProdSeven,
    },
    {
        id: 8,
        title: "Product Eight",
        description: "Black",
        price: "$44.00",
        image: ProdEight,
    },
    {
        id: 6,
        title: "Product Six",
        description: "Black",
        price: "$44.00",
        image: ProdSix,
    },
    {
        id: 7,
        title: "Product Seven",
        description: "Black",
        price: "$44.00",
        image: ProdSeven,
    },
    {
        id: 8,
        title: "Product Eight",
        description: "Black",
        price: "$44.00",
        image: ProdEight,
    },
    {
        id: 6,
        title: "Product Six",
        description: "Black",
        price: "$44.00",
        image: ProdSix,
    },
    {
        id: 7,
        title: "Product Seven",
        description: "Black",
        price: "$44.00",
        image: ProdSeven,
    },
    {
        id: 8,
        title: "Product Eight",
        description: "Black",
        price: "$44.00",
        image: ProdEight,
    },
    {
        id: 9,
        title: "Product Nine",
        description: "Black",
        price: "$44.00",
        image: ProdNine,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
    {
        id: 11,
        title: "Product Eleven",
        description: "Black",
        price: "$44.00",
        image: ProdEleven,
    },
    {
        id: 10,
        title: "Product Ten",
        description: "Black",
        price: "$44.00",
        image: ProdTen,
    },
]

export default data
